generate: reintroduce looprpc
lightninglabs/lightning-api-ng pull request #37
Opened 2024-12-19 17:24 UTC by djkazic

A previous PR fixed an error for `swapserverrpc` docs generation but broke `looprpc` docs generation. As a result, there are no docs for `looprpc.*` RPC calls.

The core of the issue is that if you do not specify an explicit source directory, the root of the `loop` repo is used which breaks the relative imports.

This patch adds a `sed` patcher that does an in-place replacement of these broken imports. Thus, the source directory can be `loop` itself -- readding the removed `looprpc` documentation.

2024-12-26 20:40 UTC, lightninglabs-deploy commented
@guggero: review reminder
@jamaljsr: review reminder

2025-01-02 20:48 UTC, lightninglabs-deploy commented
@guggero: review reminder
@jamaljsr: review reminder

2025-01-03 00:38 UTC, jamaljsr requested changes
Thanks for taking a stab at this fix. Appreciate the effort. 💪

While these changes will fix this specific issue, the code isn't as clean as I'd prefer. It's introducing Loop specific exceptions into the generic `initrepo` function. It's better if all of the customization happens via the env vars set for each repo.

After a bit of fussing with the `find` command args, I was able to come up with a simpler implementation that also addresses the problem. I've added the code suggestions below.

2025-01-03 00:38 UTC, jamaljsr commented on generate.sh
> +  proto_files=$(find . -name '*.proto' -not -name $EXCLUDE_PROTOS | tr '\n' ' ')
```suggestion
  proto_files=$(find . -name '*.proto' -not -path "$EXCLUDE_PROTOS")
```

Since loop is the only repo that uses the `EXCLUDE_PROTOS` var, we can safely modify its value to represent a path instead of a name.

2025-01-03 00:38 UTC, jamaljsr commented on generate.sh
> +
```suggestion
```

We can remove this special case.

2025-01-03 00:38 UTC, jamaljsr commented on generate.sh
>  EXCLUDE_PROTOS="server.proto -not -name common.proto"
```suggestion
PROTO_SRC_DIR=""
EXCLUDE_PROTOS="./swapserverrpc/*"
```

Exclude the `swapserverrpc` dir when finding proto files to pass to `protoc`.

2025-01-03 14:36 UTC, djkazic commented
@jamaljsr just force pushed w/ your changes

2025-01-03 16:56 UTC, jamaljsr approved these changes
tACK LGTM 🔥

Thanks for the help resolving this issue.

2025-01-03 16:58 UTC, jamaljsr commented
@guggero I see you tagged yourself for review so I'll hold off on merging this until you give the thumbs up.

2025-01-06 18:11 UTC, jamaljsr commented
Since @guggero is OOO, I am going to merge this now in order to get the Loop Docs displayed correctly on the live site.

2025-01-06 18:11 UTC, merged